### ISSUE TITLE
Reduce filesystem permissions?

### ISSUE THREAD

**Issue by lunaryorn** [flathub/com.github.geigi.cozy#3]
Hello,

I just noticed that cozy requests `filesystem=host`; I wonder why?  Would anything break if I added an override to restrict permissions to my folder of audiobooks?

Cheers

**Comment by geigi** [comment]
Hey :) overriding the permission would work just fine :) The default is access to the whole filesystem because people store audiobooks in many different locations and there is no sensible default restriction. Also a lot of People don't know how to override the permission and therefor this would lead to a lot of support request on my side because people cannot find their files in Cozy.

**Comment by lunaryorn** [comment]
Thanks for the quick answer🙏
