### ISSUE TITLE
Remove "--talk-name=org.gtk.vfs.*"

### ISSUE THREAD

**Issue by hadess** [flathub/com.github.geigi.cozy#4]
This application probably doesn't need to talk to gvfs.

It has:
```
    "--talk-name=org.gtk.vfs.*"
```
in its manifest, but lacks `"--talk-name=org.gtk.vfs"` for this to work. You probably want to remove this statement and keep `"--filesystem=xdg-run/gvfs"` so it can access files from remote shares.

**Comment by geigi** [comment]
Thanks for reporting :) I'll test and fix this issue soon.

**Comment by geigi** [comment]
I've just had a look. Cozy does indeed need to talk to gvfs because it detects whether a drive is mounted that is part of Cozy's media library. 
But this feature was broken in the flatpak similar to this issue in Gnome Photos: https://gitlab.gnome.org/GNOME/gnome-photos/-/merge_requests/25
Thanks for raising attention to this issue! I'll fix it in Cozy's case by adding `"--talk-name=org.gtk.vfs"` aswell.

**Comment by hadess** [comment]
Sorry for not getting back to you sooner, but:
https://github.com/flathub/flathub/issues/2180#issuecomment-811984901

So this change did nothing, and is unlikely to have fixed the problem of not being able to access the removable media.
Did you test it?

If you're going to access that mounted media, maybe you were missing `--filesystem=/run/media` instead?

**Comment by geigi** [comment]
Hi!

Your suggestion in the issue did not impact the functionality of accessing files on external media so that was all good.

But there are some other features which where not working in the flatpak (but did not work before your suggestion as well):

- getting an event when a new storage device was mounted 
- getting an event when a storage device is unmounted
- testing whether a path is on an actual unmountable storage location

These features are build using `Gio.VolumeMonitor` and require communication with `org.gtk.vfs`. After adding this to the flatpak permissions those features did work again.

**Comment by hadess** [comment]
> These features are build using `Gio.VolumeMonitor` and require communication with `org.gtk.vfs`. After adding this to the flatpak permissions those features did work again.

There's nothing on the session bus called `org.gtk.vfs`... You'll also need to add `"--filesystem=xdg-run/gvfsd"` if you want for access any of the gvfs daemons with newer versions of gvfs on the host though. See https://github.com/flathub/flathub/issues/2180#issue-841878429

**Comment by geigi** [comment]
Ok then I probably misunderstood something. I'll test this soon and keep the issue updated :)

**Comment by geigi** [comment]
Ah my bad I just noticed I tested without `"--talk-name=org.gtk.vfs.*"` which then broke the features mentioned above, sorry...

**Comment by geigi** [comment]
I've removed `"--talk-name=org.gtk.vfs` and added `--filesystem=xdg-run/gvfsd` as you suggested and all features are working fine now. I think this issue is now resolved then?

Commit: https://github.com/flathub/com.github.geigi.cozy/commit/3a29e80b80fc54d9ca95f6f08f254fb19b4e464a

**Comment by geigi** [comment]
I think this issue is resolved now, feel free to reopen if it isn't :)
